test(facet actions): facet actions test
unbxd/react-search-JS-SDK pull request #139
Opened 2021-01-20 08:49 UTC by deepunbxd005

2021-01-20 16:55 UTC, vikramgupta1988 requested changes

2021-01-20 16:55 UTC, vikramgupta1988 commented on src/modules/textFacets/__tests__/textFacets.test.js
> +test('Test text facet actions with custom onApply method', async () => {
custom onCLear

2021-01-20 16:55 UTC, vikramgupta1988 commented on src/modules/textFacets/__tests__/textFacets.test.js
> +                <FacetActions showClearFilter={false} />
By default, is it true?

2021-01-20 17:05 UTC, deepunbxd005 commented on src/modules/textFacets/__tests__/textFacets.test.js
> +                <FacetActions showClearFilter={false} />
yes

2021-01-20 17:05 UTC, deepunbxd005 commented on src/modules/textFacets/__tests__/textFacets.test.js
> +                <FacetActions showClearFilter={false} />
as we can see in the snapshot created

2021-01-20 17:08 UTC, deepunbxd005 commented on src/modules/textFacets/__tests__/textFacets.test.js
> +test('Test text facet actions with custom onApply method', async () => {
done

2021-01-20 18:14 UTC, vikramgupta1988 approved these changes

2021-01-20 18:15 UTC, merged

2021-01-21 12:40 UTC, sanjithkumar017 commented
:tada: This PR is included in version 0.0.40 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@unbxd-ui/react-search-sdk/v/0.0.40)
- [GitHub release](https://github.com/unbxd/react-search-JS-SDK/releases/tag/v0.0.40)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: